
-- Migration to add missing task fields
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS progress_percentage INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimated_hours INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_hours INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS ai_priority_score INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS ai_reasoning TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS ai_next_action TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS ai_analyzed_at TIMESTAMP;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS dependencies JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS compliance_requirement TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS evidence_required BOOLEAN DEFAULT false;
